######################################################################################################
## Travis-CI control file                                                                           ##
##                                                                                                  ##
## Date       Developer           Comments                                                          ##
## ========== =================== ================================================================= ##
## 2020-06-06 Arnd@SV-Zanshin     Cleaned up comments                                               ##
## 2020-05-11 Arnd@SV-Zanshin     Removed Adafruit libraries which now caused Travis to fail        ##
## 2019-01-23 Arnd@SV-Zanshin     Corrected PRETTYNAME                                              ##
## 2019-01-20 Arnd@SV-Zanshin     Linked to Adafruit script rather than manually defining all tests ##
## 2019-01-19 Arnd@SV-Zanshin     Initial coding                                                    ##
##                                                                                                  ##
######################################################################################################
language: c
sudo: false

# Blacklist
branches:
  except:
    - gh-pages
    
git:
  depth: false
  quiet: true
env:
  global:
    - PRETTYNAME="VCNL4010 Arduino Library"
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:

script:
  - build_main_platforms

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
